instr_xx_tab
                dc.w    _00-_00
                dc.w    _01-_00
                dc.w    _02-_00
                dc.w    _03-_00
                dc.w    _04-_00
                dc.w    _05-_00
                dc.w    _06-_00
                dc.w    _07-_00
                dc.w    _08-_00
                dc.w    _09-_00
                dc.w    _0A-_00
                dc.w    _0B-_00
                dc.w    _0C-_00
                dc.w    _0D-_00
                dc.w    _0E-_00
                dc.w    _0F-_00
                dc.w    _10-_00
                dc.w    _11-_00
                dc.w    _12-_00
                dc.w    _13-_00
                dc.w    _14-_00
                dc.w    _15-_00
                dc.w    _16-_00
                dc.w    _17-_00
                dc.w    _18-_00
                dc.w    _19-_00
                dc.w    _1A-_00
                dc.w    _1B-_00
                dc.w    _1C-_00
                dc.w    _1D-_00
                dc.w    _1E-_00
                dc.w    _1F-_00
                dc.w    _20-_00
                dc.w    _21-_00
                dc.w    _22-_00
                dc.w    _23-_00
                dc.w    _24-_00
                dc.w    _25-_00
                dc.w    _26-_00
                dc.w    _27-_00
                dc.w    _28-_00
                dc.w    _29-_00
                dc.w    _2A-_00
                dc.w    _2B-_00
                dc.w    _2C-_00
                dc.w    _2D-_00
                dc.w    _2E-_00
                dc.w    _2F-_00
                dc.w    _30-_00
                dc.w    _31-_00
                dc.w    _32-_00
                dc.w    _33-_00
                dc.w    _34-_00
                dc.w    _35-_00
                dc.w    _36-_00
                dc.w    _37-_00
                dc.w    _38-_00
                dc.w    _39-_00
                dc.w    _3A-_00
                dc.w    _3B-_00
                dc.w    _3C-_00
                dc.w    _3D-_00
                dc.w    _3E-_00
                dc.w    _3F-_00

                dc.w    _40-_00
                dc.w    _41-_00
                dc.w    _42-_00
                dc.w    _43-_00
                dc.w    _44-_00
                dc.w    _45-_00
                dc.w    _46-_00
                dc.w    _47-_00
                dc.w    _48-_00
                dc.w    _49-_00
                dc.w    _4A-_00
                dc.w    _4B-_00
                dc.w    _4C-_00
                dc.w    _4D-_00
                dc.w    _4E-_00
                dc.w    _4F-_00
                dc.w    _50-_00
                dc.w    _51-_00
                dc.w    _52-_00
                dc.w    _53-_00
                dc.w    _54-_00
                dc.w    _55-_00
                dc.w    _56-_00
                dc.w    _57-_00
                dc.w    _58-_00
                dc.w    _59-_00
                dc.w    _5A-_00
                dc.w    _5B-_00
                dc.w    _5C-_00
                dc.w    _5D-_00
                dc.w    _5E-_00
                dc.w    _5F-_00
                dc.w    _60-_00
                dc.w    _61-_00
                dc.w    _62-_00
                dc.w    _63-_00
                dc.w    _64-_00
                dc.w    _65-_00
                dc.w    _66-_00
                dc.w    _67-_00
                dc.w    _68-_00
                dc.w    _69-_00
                dc.w    _6A-_00
                dc.w    _6B-_00
                dc.w    _6C-_00
                dc.w    _6D-_00
                dc.w    _6E-_00
                dc.w    _6F-_00
                dc.w    _70-_00
                dc.w    _71-_00
                dc.w    _72-_00
                dc.w    _73-_00
                dc.w    _74-_00
                dc.w    _75-_00
                dc.w    _76-_00
                dc.w    _77-_00
                dc.w    _78-_00
                dc.w    _79-_00
                dc.w    _7A-_00
                dc.w    _7B-_00
                dc.w    _7C-_00
                dc.w    _7D-_00
                dc.w    _7E-_00
                dc.w    _7F-_00

                dc.w    _80-_00
                dc.w    _81-_00
                dc.w    _82-_00
                dc.w    _83-_00
                dc.w    _84-_00
                dc.w    _85-_00
                dc.w    _86-_00
                dc.w    _87-_00
                dc.w    _88-_00
                dc.w    _89-_00
                dc.w    _8A-_00
                dc.w    _8B-_00
                dc.w    _8C-_00
                dc.w    _8D-_00
                dc.w    _8E-_00
                dc.w    _8F-_00
                dc.w    _90-_00
                dc.w    _91-_00
                dc.w    _92-_00
                dc.w    _93-_00
                dc.w    _94-_00
                dc.w    _95-_00
                dc.w    _96-_00
                dc.w    _97-_00
                dc.w    _98-_00
                dc.w    _99-_00
                dc.w    _9A-_00
                dc.w    _9B-_00
                dc.w    _9C-_00
                dc.w    _9D-_00
                dc.w    _9E-_00
                dc.w    _9F-_00
                dc.w    _A0-_00
                dc.w    _A1-_00
                dc.w    _A2-_00
                dc.w    _A3-_00
                dc.w    _A4-_00
                dc.w    _A5-_00
                dc.w    _A6-_00
                dc.w    _A7-_00
                dc.w    _A8-_00
                dc.w    _A9-_00
                dc.w    _AA-_00
                dc.w    _AB-_00
                dc.w    _AC-_00
                dc.w    _AD-_00
                dc.w    _AE-_00
                dc.w    _AF-_00
                dc.w    _B0-_00
                dc.w    _B1-_00
                dc.w    _B2-_00
                dc.w    _B3-_00
                dc.w    _B4-_00
                dc.w    _B5-_00
                dc.w    _B6-_00
                dc.w    _B7-_00
                dc.w    _B8-_00
                dc.w    _B9-_00
                dc.w    _BA-_00
                dc.w    _BB_-_00
                dc.w    _BC-_00
                dc.w    _BD-_00
                dc.w    _BE-_00
                dc.w    _BF-_00

                dc.w    _C0-_00
                dc.w    _C1-_00
                dc.w    _C2-_00
                dc.w    _C3-_00
                dc.w    _C4-_00
                dc.w    _C5-_00
                dc.w    _C6-_00
                dc.w    _C7-_00
                dc.w    _C8-_00
                dc.w    _C9-_00
                dc.w    _CA-_00
                dc.w    _CB-_00
                dc.w    _CC-_00
                dc.w    _CD-_00
                dc.w    _CE-_00
                dc.w    _CF-_00
                dc.w    _D0-_00
                dc.w    _D1-_00
                dc.w    _D2-_00
                dc.w    _D3-_00
                dc.w    _D4-_00
                dc.w    _D5-_00
                dc.w    _D6-_00
                dc.w    _D7-_00
                dc.w    _D8-_00
                dc.w    _D9-_00
                dc.w    _DA-_00
                dc.w    _DB-_00
                dc.w    _DC-_00
                dc.w    _DD-_00
                dc.w    _DE-_00
                dc.w    _DF-_00
                dc.w    _E0-_00
                dc.w    _E1-_00
                dc.w    _E2-_00
                dc.w    _E3-_00
                dc.w    _E4-_00
                dc.w    _E5-_00
                dc.w    _E6-_00
                dc.w    _E7-_00
                dc.w    _E8-_00
                dc.w    _E9-_00
                dc.w    _EA-_00
                dc.w    _EB-_00
                dc.w    _EC-_00
                dc.w    _ED-_00
                dc.w    _EE-_00
                dc.w    _EF-_00
                dc.w    _F0-_00
                dc.w    _F1-_00
                dc.w    _F2-_00
                dc.w    _F3-_00
                dc.w    _F4-_00
                dc.w    _F5-_00
                dc.w    _F6-_00
                dc.w    _F7-_00
                dc.w    _F8-_00
                dc.w    _F9-_00
                dc.w    _FA-_00
                dc.w    _FB-_00
                dc.w    _FC-_00
                dc.w    _FD-_00
                dc.w    _FE-_00
                dc.w    _FF-_00


                dc.w    _CB00-_00
                dc.w    _CB01-_00
                dc.w    _CB02-_00
                dc.w    _CB03-_00
                dc.w    _CB04-_00
                dc.w    _CB05-_00
                dc.w    _CB06-_00
                dc.w    _CB07-_00
                dc.w    _CB08-_00
                dc.w    _CB09-_00
                dc.w    _CB0A-_00
                dc.w    _CB0B-_00
                dc.w    _CB0C-_00
                dc.w    _CB0D-_00
                dc.w    _CB0E-_00
                dc.w    _CB0F-_00

                dc.w    _CB10-_00
                dc.w    _CB11-_00
                dc.w    _CB12-_00
                dc.w    _CB13-_00
                dc.w    _CB14-_00
                dc.w    _CB15-_00
                dc.w    _CB16-_00
                dc.w    _CB17-_00
                dc.w    _CB18-_00
                dc.w    _CB19-_00
                dc.w    _CB1A-_00
                dc.w    _CB1B-_00
                dc.w    _CB1C-_00
                dc.w    _CB1D-_00
                dc.w    _CB1E-_00
                dc.w    _CB1F-_00

                dc.w    _CB20-_00
                dc.w    _CB21-_00
                dc.w    _CB22-_00
                dc.w    _CB23-_00
                dc.w    _CB24-_00
                dc.w    _CB25-_00
                dc.w    _CB26-_00
                dc.w    _CB27-_00
                dc.w    _CB28-_00
                dc.w    _CB29-_00
                dc.w    _CB2A-_00
                dc.w    _CB2B-_00
                dc.w    _CB2C-_00
                dc.w    _CB2D-_00
                dc.w    _CB2E-_00
                dc.w    _CB2F-_00
                           
                dc.w    _CB30-_00
                dc.w    _CB31-_00
                dc.w    _CB32-_00
                dc.w    _CB33-_00
                dc.w    _CB34-_00
                dc.w    _CB35-_00
                dc.w    _CB36-_00
                dc.w    _CB37-_00
                dc.w    _CB38-_00
                dc.w    _CB39-_00
                dc.w    _CB3A-_00
                dc.w    _CB3B-_00
                dc.w    _CB3C-_00
                dc.w    _CB3D-_00
                dc.w    _CB3E-_00
                dc.w    _CB3F-_00

                dc.w    _CB40-_00
                dc.w    _CB41-_00
                dc.w    _CB42-_00
                dc.w    _CB43-_00
                dc.w    _CB44-_00
                dc.w    _CB45-_00
                dc.w    _CB46-_00
                dc.w    _CB47-_00
                dc.w    _CB48-_00
                dc.w    _CB49-_00
                dc.w    _CB4A-_00
                dc.w    _CB4B-_00
                dc.w    _CB4C-_00
                dc.w    _CB4D-_00
                dc.w    _CB4E-_00
                dc.w    _CB4F-_00

                dc.w    _CB50-_00
                dc.w    _CB51-_00
                dc.w    _CB52-_00
                dc.w    _CB53-_00
                dc.w    _CB54-_00
                dc.w    _CB55-_00
                dc.w    _CB56-_00
                dc.w    _CB57-_00
                dc.w    _CB58-_00
                dc.w    _CB59-_00
                dc.w    _CB5A-_00
                dc.w    _CB5B-_00
                dc.w    _CB5C-_00
                dc.w    _CB5D-_00
                dc.w    _CB5E-_00
                dc.w    _CB5F-_00

                dc.w    _CB60-_00
                dc.w    _CB61-_00
                dc.w    _CB62-_00
                dc.w    _CB63-_00
                dc.w    _CB64-_00
                dc.w    _CB65-_00
                dc.w    _CB66-_00
                dc.w    _CB67-_00
                dc.w    _CB68-_00
                dc.w    _CB69-_00
                dc.w    _CB6A-_00
                dc.w    _CB6B-_00
                dc.w    _CB6C-_00
                dc.w    _CB6D-_00
                dc.w    _CB6E-_00
                dc.w    _CB6F-_00

                dc.w    _CB70-_00
                dc.w    _CB71-_00
                dc.w    _CB72-_00
                dc.w    _CB73-_00
                dc.w    _CB74-_00
                dc.w    _CB75-_00
                dc.w    _CB76-_00
                dc.w    _CB77-_00
                dc.w    _CB78-_00
                dc.w    _CB79-_00
                dc.w    _CB7A-_00
                dc.w    _CB7B-_00
                dc.w    _CB7C-_00
                dc.w    _CB7D-_00
                dc.w    _CB7E-_00
                dc.w    _CB7F-_00

                dc.w    _CB80-_00
                dc.w    _CB81-_00
                dc.w    _CB82-_00
                dc.w    _CB83-_00
                dc.w    _CB84-_00
                dc.w    _CB85-_00
                dc.w    _CB86-_00
                dc.w    _CB87-_00
                dc.w    _CB88-_00
                dc.w    _CB89-_00
                dc.w    _CB8A-_00
                dc.w    _CB8B-_00
                dc.w    _CB8C-_00
                dc.w    _CB8D-_00
                dc.w    _CB8E-_00
                dc.w    _CB8F-_00

                dc.w    _CB90-_00
                dc.w    _CB91-_00
                dc.w    _CB92-_00
                dc.w    _CB93-_00
                dc.w    _CB94-_00
                dc.w    _CB95-_00
                dc.w    _CB96-_00
                dc.w    _CB97-_00
                dc.w    _CB98-_00
                dc.w    _CB99-_00
                dc.w    _CB9A-_00
                dc.w    _CB9B-_00
                dc.w    _CB9C-_00
                dc.w    _CB9D-_00
                dc.w    _CB9E-_00
                dc.w    _CB9F-_00
                           
                dc.w    _CBA0-_00
                dc.w    _CBA1-_00
                dc.w    _CBA2-_00
                dc.w    _CBA3-_00
                dc.w    _CBA4-_00
                dc.w    _CBA5-_00
                dc.w    _CBA6-_00
                dc.w    _CBA7-_00
                dc.w    _CBA8-_00
                dc.w    _CBA9-_00
                dc.w    _CBAA-_00
                dc.w    _CBAB-_00
                dc.w    _CBAC-_00
                dc.w    _CBAD-_00
                dc.w    _CBAE-_00
                dc.w    _CBAF-_00

                dc.w    _CBB0-_00
                dc.w    _CBB1-_00
                dc.w    _CBB2-_00
                dc.w    _CBB3-_00
                dc.w    _CBB4-_00
                dc.w    _CBB5-_00
                dc.w    _CBB6-_00
                dc.w    _CBB7-_00
                dc.w    _CBB8-_00
                dc.w    _CBB9-_00
                dc.w    _CBBA-_00
                dc.w    _CBBB-_00
                dc.w    _CBBC-_00
                dc.w    _CBBD-_00
                dc.w    _CBBE-_00
                dc.w    _CBBF-_00

                dc.w    _CBC0-_00
                dc.w    _CBC1-_00
                dc.w    _CBC2-_00
                dc.w    _CBC3-_00
                dc.w    _CBC4-_00
                dc.w    _CBC5-_00
                dc.w    _CBC6-_00
                dc.w    _CBC7-_00
                dc.w    _CBC8-_00
                dc.w    _CBC9-_00
                dc.w    _CBCA-_00
                dc.w    _CBCB-_00
                dc.w    _CBCC-_00
                dc.w    _CBCD-_00
                dc.w    _CBCE-_00
                dc.w    _CBCF-_00

                dc.w    _CBD0-_00
                dc.w    _CBD1-_00
                dc.w    _CBD2-_00
                dc.w    _CBD3-_00
                dc.w    _CBD4-_00
                dc.w    _CBD5-_00
                dc.w    _CBD6-_00
                dc.w    _CBD7-_00
                dc.w    _CBD8-_00
                dc.w    _CBD9-_00
                dc.w    _CBDA-_00
                dc.w    _CBDB-_00
                dc.w    _CBDC-_00
                dc.w    _CBDD-_00
                dc.w    _CBDE-_00
                dc.w    _CBDF-_00

                dc.w    _CBE0-_00
                dc.w    _CBE1-_00
                dc.w    _CBE2-_00
                dc.w    _CBE3-_00
                dc.w    _CBE4-_00
                dc.w    _CBE5-_00
                dc.w    _CBE6-_00
                dc.w    _CBE7-_00
                dc.w    _CBE8-_00
                dc.w    _CBE9-_00
                dc.w    _CBEA-_00
                dc.w    _CBEB-_00
                dc.w    _CBEC-_00
                dc.w    _CBED-_00
                dc.w    _CBEE-_00
                dc.w    _CBEF-_00

                dc.w    _CBF0-_00
                dc.w    _CBF1-_00
                dc.w    _CBF2-_00
                dc.w    _CBF3-_00
                dc.w    _CBF4-_00
                dc.w    _CBF5-_00
                dc.w    _CBF6-_00
                dc.w    _CBF7-_00
                dc.w    _CBF8-_00
                dc.w    _CBF9-_00
                dc.w    _CBFA-_00
                dc.w    _CBFB-_00
                dc.w    _CBFC-_00
                dc.w    _CBFD-_00
                dc.w    _CBFE-_00
                dc.w    _CBFF-_00

                dc.w    _ED00-_00
                dc.w    _ED01-_00
                dc.w    _ED02-_00
                dc.w    _ED03-_00
                dc.w    _ED04-_00
                dc.w    _ED05-_00
                dc.w    _ED06-_00
                dc.w    _ED07-_00
                dc.w    _ED08-_00
                dc.w    _ED09-_00
                dc.w    _ED0A-_00
                dc.w    _ED0B-_00
                dc.w    _ED0C-_00
                dc.w    _ED0D-_00
                dc.w    _ED0E-_00
                dc.w    _ED0F-_00

                dc.w    _ED10-_00
                dc.w    _ED11-_00
                dc.w    _ED12-_00
                dc.w    _ED13-_00
                dc.w    _ED14-_00
                dc.w    _ED15-_00
                dc.w    _ED16-_00
                dc.w    _ED17-_00
                dc.w    _ED18-_00
                dc.w    _ED19-_00
                dc.w    _ED1A-_00
                dc.w    _ED1B-_00
                dc.w    _ED1C-_00
                dc.w    _ED1D-_00
                dc.w    _ED1E-_00
                dc.w    _ED1F-_00

                dc.w    _ED20-_00
                dc.w    _ED21-_00
                dc.w    _ED22-_00
                dc.w    _ED23-_00
                dc.w    _ED24-_00
                dc.w    _ED25-_00
                dc.w    _ED26-_00
                dc.w    _ED27-_00
                dc.w    _ED28-_00
                dc.w    _ED29-_00
                dc.w    _ED2A-_00
                dc.w    _ED2B-_00
                dc.w    _ED2C-_00
                dc.w    _ED2D-_00
                dc.w    _ED2E-_00
                dc.w    _ED2F-_00
                           
                dc.w    _ED30-_00
                dc.w    _ED31-_00
                dc.w    _ED32-_00
                dc.w    _ED33-_00
                dc.w    _ED34-_00
                dc.w    _ED35-_00
                dc.w    _ED36-_00
                dc.w    _ED37-_00
                dc.w    _ED38-_00
                dc.w    _ED39-_00
                dc.w    _ED3A-_00
                dc.w    _ED3B-_00
                dc.w    _ED3C-_00
                dc.w    _ED3D-_00
                dc.w    _ED3E-_00
                dc.w    _ED3F-_00

                dc.w    _ED40-_00
                dc.w    _ED41-_00
                dc.w    _ED42-_00
                dc.w    _ED43-_00
                dc.w    _ED44-_00
                dc.w    _ED45-_00
                dc.w    _ED46-_00
                dc.w    _ED47-_00
                dc.w    _ED48-_00
                dc.w    _ED49-_00
                dc.w    _ED4A-_00
                dc.w    _ED4B-_00
                dc.w    _ED4C-_00
                dc.w    _ED4D-_00
                dc.w    _ED4E-_00
                dc.w    _ED4F-_00

                dc.w    _ED50-_00
                dc.w    _ED51-_00
                dc.w    _ED52-_00
                dc.w    _ED53-_00
                dc.w    _ED54-_00
                dc.w    _ED55-_00
                dc.w    _ED56-_00
                dc.w    _ED57-_00
                dc.w    _ED58-_00
                dc.w    _ED59-_00
                dc.w    _ED5A-_00
                dc.w    _ED5B-_00
                dc.w    _ED5C-_00
                dc.w    _ED5D-_00
                dc.w    _ED5E-_00
                dc.w    _ED5F-_00

                dc.w    _ED60-_00
                dc.w    _ED61-_00
                dc.w    _ED62-_00
                dc.w    _ED63-_00
                dc.w    _ED64-_00
                dc.w    _ED65-_00
                dc.w    _ED66-_00
                dc.w    _ED67-_00
                dc.w    _ED68-_00
                dc.w    _ED69-_00
                dc.w    _ED6A-_00
                dc.w    _ED6B-_00
                dc.w    _ED6C-_00
                dc.w    _ED6D-_00
                dc.w    _ED6E-_00
                dc.w    _ED6F-_00

                dc.w    _ED70-_00
                dc.w    _ED71-_00
                dc.w    _ED72-_00
                dc.w    _ED73-_00
                dc.w    _ED74-_00
                dc.w    _ED75-_00
                dc.w    _ED76-_00
                dc.w    _ED77-_00
                dc.w    _ED78-_00
                dc.w    _ED79-_00
                dc.w    _ED7A-_00
                dc.w    _ED7B-_00
                dc.w    _ED7C-_00
                dc.w    _ED7D-_00
                dc.w    _ED7E-_00
                dc.w    _ED7F-_00

                dc.w    _ED80-_00
                dc.w    _ED81-_00
                dc.w    _ED82-_00
                dc.w    _ED83-_00
                dc.w    _ED84-_00
                dc.w    _ED85-_00
                dc.w    _ED86-_00
                dc.w    _ED87-_00
                dc.w    _ED88-_00
                dc.w    _ED89-_00
                dc.w    _ED8A-_00
                dc.w    _ED8B-_00
                dc.w    _ED8C-_00
                dc.w    _ED8D-_00
                dc.w    _ED8E-_00
                dc.w    _ED8F-_00

                dc.w    _ED90-_00
                dc.w    _ED91-_00
                dc.w    _ED92-_00
                dc.w    _ED93-_00
                dc.w    _ED94-_00
                dc.w    _ED95-_00
                dc.w    _ED96-_00
                dc.w    _ED97-_00
                dc.w    _ED98-_00
                dc.w    _ED99-_00
                dc.w    _ED9A-_00
                dc.w    _ED9B-_00
                dc.w    _ED9C-_00
                dc.w    _ED9D-_00
                dc.w    _ED9E-_00
                dc.w    _ED9F-_00
                           
                dc.w    _EDA0-_00
                dc.w    _EDA1-_00
                dc.w    _EDA2-_00
                dc.w    _EDA3-_00
                dc.w    _EDA4-_00
                dc.w    _EDA5-_00
                dc.w    _EDA6-_00
                dc.w    _EDA7-_00
                dc.w    _EDA8-_00
                dc.w    _EDA9-_00
                dc.w    _EDAA-_00
                dc.w    _EDAB-_00
                dc.w    _EDAC-_00
                dc.w    _EDAD-_00
                dc.w    _EDAE-_00
                dc.w    _EDAF-_00

                dc.w    _EDB0-_00
                dc.w    _EDB1-_00
                dc.w    _EDB2-_00
                dc.w    _EDB3-_00
                dc.w    _EDB4-_00
                dc.w    _EDB5-_00
                dc.w    _EDB6-_00
                dc.w    _EDB7-_00
                dc.w    _EDB8-_00
                dc.w    _EDB9-_00
                dc.w    _EDBA-_00
                dc.w    _EDBB-_00
                dc.w    _EDBC-_00
                dc.w    _EDBD-_00
                dc.w    _EDBE-_00
                dc.w    _EDBF-_00

                dc.w    _EDC0-_00
                dc.w    _EDC1-_00
                dc.w    _EDC2-_00
                dc.w    _EDC3-_00
                dc.w    _EDC4-_00
                dc.w    _EDC5-_00
                dc.w    _EDC6-_00
                dc.w    _EDC7-_00
                dc.w    _EDC8-_00
                dc.w    _EDC9-_00
                dc.w    _EDCA-_00
                dc.w    _EDCB-_00
                dc.w    _EDCC-_00
                dc.w    _EDCD-_00
                dc.w    _EDCE-_00
                dc.w    _EDCF-_00

                dc.w    _EDD0-_00
                dc.w    _EDD1-_00
                dc.w    _EDD2-_00
                dc.w    _EDD3-_00
                dc.w    _EDD4-_00
                dc.w    _EDD5-_00
                dc.w    _EDD6-_00
                dc.w    _EDD7-_00
                dc.w    _EDD8-_00
                dc.w    _EDD9-_00
                dc.w    _EDDA-_00
                dc.w    _EDDB-_00
                dc.w    _EDDC-_00
                dc.w    _EDDD-_00
                dc.w    _EDDE-_00
                dc.w    _EDDF-_00

                dc.w    _EDE0-_00
                dc.w    _EDE1-_00
                dc.w    _EDE2-_00
                dc.w    _EDE3-_00
                dc.w    _EDE4-_00
                dc.w    _EDE5-_00
                dc.w    _EDE6-_00
                dc.w    _EDE7-_00
                dc.w    _EDE8-_00
                dc.w    _EDE9-_00
                dc.w    _EDEA-_00
                dc.w    _EDEB-_00
                dc.w    _EDEC-_00
                dc.w    _EDED-_00
                dc.w    _EDEE-_00
                dc.w    _EDEF-_00

                dc.w    _EDF0-_00
                dc.w    _EDF1-_00
                dc.w    _EDF2-_00
                dc.w    _EDF3-_00
                dc.w    _EDF4-_00
                dc.w    _EDF5-_00
                dc.w    _EDF6-_00
                dc.w    _EDF7-_00
                dc.w    _EDF8-_00
                dc.w    _EDF9-_00
                dc.w    _EDFA-_00
                dc.w    _EDFB-_00
                dc.w    _EDFC-_00
                dc.w    _EDFD-_00
                dc.w    _EDFE-_00
                dc.w    _EDFF-_00

                dc.w    _DD00-_00
                dc.w    _DD01-_00
                dc.w    _DD02-_00
                dc.w    _DD03-_00
                dc.w    _DD04-_00
                dc.w    _DD05-_00
                dc.w    _DD06-_00
                dc.w    _DD07-_00
                dc.w    _DD08-_00
                dc.w    _DD09-_00
                dc.w    _DD0A-_00
                dc.w    _DD0B-_00
                dc.w    _DD0C-_00
                dc.w    _DD0D-_00
                dc.w    _DD0E-_00
                dc.w    _DD0F-_00

                dc.w    _DD10-_00
                dc.w    _DD11-_00
                dc.w    _DD12-_00
                dc.w    _DD13-_00
                dc.w    _DD14-_00
                dc.w    _DD15-_00
                dc.w    _DD16-_00
                dc.w    _DD17-_00
                dc.w    _DD18-_00
                dc.w    _DD19-_00
                dc.w    _DD1A-_00
                dc.w    _DD1B-_00
                dc.w    _DD1C-_00
                dc.w    _DD1D-_00
                dc.w    _DD1E-_00
                dc.w    _DD1F-_00

                dc.w    _DD20-_00
                dc.w    _DD21-_00
                dc.w    _DD22-_00
                dc.w    _DD23-_00
                dc.w    _DD24-_00
                dc.w    _DD25-_00
                dc.w    _DD26-_00
                dc.w    _DD27-_00
                dc.w    _DD28-_00
                dc.w    _DD29-_00
                dc.w    _DD2A-_00
                dc.w    _DD2B-_00
                dc.w    _DD2C-_00
                dc.w    _DD2D-_00
                dc.w    _DD2E-_00
                dc.w    _DD2F-_00
                           
                dc.w    _DD30-_00
                dc.w    _DD31-_00
                dc.w    _DD32-_00
                dc.w    _DD33-_00
                dc.w    _DD34-_00
                dc.w    _DD35-_00
                dc.w    _DD36-_00
                dc.w    _DD37-_00
                dc.w    _DD38-_00
                dc.w    _DD39-_00
                dc.w    _DD3A-_00
                dc.w    _DD3B-_00
                dc.w    _DD3C-_00
                dc.w    _DD3D-_00
                dc.w    _DD3E-_00
                dc.w    _DD3F-_00

                dc.w    _DD40-_00
                dc.w    _DD41-_00
                dc.w    _DD42-_00
                dc.w    _DD43-_00
                dc.w    _DD44-_00
                dc.w    _DD45-_00
                dc.w    _DD46-_00
                dc.w    _DD47-_00
                dc.w    _DD48-_00
                dc.w    _DD49-_00
                dc.w    _DD4A-_00
                dc.w    _DD4B-_00
                dc.w    _DD4C-_00
                dc.w    _DD4D-_00
                dc.w    _DD4E-_00
                dc.w    _DD4F-_00

                dc.w    _DD50-_00
                dc.w    _DD51-_00
                dc.w    _DD52-_00
                dc.w    _DD53-_00
                dc.w    _DD54-_00
                dc.w    _DD55-_00
                dc.w    _DD56-_00
                dc.w    _DD57-_00
                dc.w    _DD58-_00
                dc.w    _DD59-_00
                dc.w    _DD5A-_00
                dc.w    _DD5B-_00
                dc.w    _DD5C-_00
                dc.w    _DD5D-_00
                dc.w    _DD5E-_00
                dc.w    _DD5F-_00

                dc.w    _DD60-_00
                dc.w    _DD61-_00
                dc.w    _DD62-_00
                dc.w    _DD63-_00
                dc.w    _DD64-_00
                dc.w    _DD65-_00
                dc.w    _DD66-_00
                dc.w    _DD67-_00
                dc.w    _DD68-_00
                dc.w    _DD69-_00
                dc.w    _DD6A-_00
                dc.w    _DD6B-_00
                dc.w    _DD6C-_00
                dc.w    _DD6D-_00
                dc.w    _DD6E-_00
                dc.w    _DD6F-_00

                dc.w    _DD70-_00
                dc.w    _DD71-_00
                dc.w    _DD72-_00
                dc.w    _DD73-_00
                dc.w    _DD74-_00
                dc.w    _DD75-_00
                dc.w    _DD76-_00
                dc.w    _DD77-_00
                dc.w    _DD78-_00
                dc.w    _DD79-_00
                dc.w    _DD7A-_00
                dc.w    _DD7B-_00
                dc.w    _DD7C-_00
                dc.w    _DD7D-_00
                dc.w    _DD7E-_00
                dc.w    _DD7F-_00

                dc.w    _DD80-_00
                dc.w    _DD81-_00
                dc.w    _DD82-_00
                dc.w    _DD83-_00
                dc.w    _DD84-_00
                dc.w    _DD85-_00
                dc.w    _DD86-_00
                dc.w    _DD87-_00
                dc.w    _DD88-_00
                dc.w    _DD89-_00
                dc.w    _DD8A-_00
                dc.w    _DD8B-_00
                dc.w    _DD8C-_00
                dc.w    _DD8D-_00
                dc.w    _DD8E-_00
                dc.w    _DD8F-_00

                dc.w    _DD90-_00
                dc.w    _DD91-_00
                dc.w    _DD92-_00
                dc.w    _DD93-_00
                dc.w    _DD94-_00
                dc.w    _DD95-_00
                dc.w    _DD96-_00
                dc.w    _DD97-_00
                dc.w    _DD98-_00
                dc.w    _DD99-_00
                dc.w    _DD9A-_00
                dc.w    _DD9B-_00
                dc.w    _DD9C-_00
                dc.w    _DD9D-_00
                dc.w    _DD9E-_00
                dc.w    _DD9F-_00
                           
                dc.w    _DDA0-_00
                dc.w    _DDA1-_00
                dc.w    _DDA2-_00
                dc.w    _DDA3-_00
                dc.w    _DDA4-_00
                dc.w    _DDA5-_00
                dc.w    _DDA6-_00
                dc.w    _DDA7-_00
                dc.w    _DDA8-_00
                dc.w    _DDA9-_00
                dc.w    _DDAA-_00
                dc.w    _DDAB-_00
                dc.w    _DDAC-_00
                dc.w    _DDAD-_00
                dc.w    _DDAE-_00
                dc.w    _DDAF-_00

                dc.w    _DDB0-_00
                dc.w    _DDB1-_00
                dc.w    _DDB2-_00
                dc.w    _DDB3-_00
                dc.w    _DDB4-_00
                dc.w    _DDB5-_00
                dc.w    _DDB6-_00
                dc.w    _DDB7-_00
                dc.w    _DDB8-_00
                dc.w    _DDB9-_00
                dc.w    _DDBA-_00
                dc.w    _DDBB-_00
                dc.w    _DDBC-_00
                dc.w    _DDBD-_00
                dc.w    _DDBE-_00
                dc.w    _DDBF-_00

                dc.w    _DDC0-_00
                dc.w    _DDC1-_00
                dc.w    _DDC2-_00
                dc.w    _DDC3-_00
                dc.w    _DDC4-_00
                dc.w    _DDC5-_00
                dc.w    _DDC6-_00
                dc.w    _DDC7-_00
                dc.w    _DDC8-_00
                dc.w    _DDC9-_00
                dc.w    _DDCA-_00
                dc.w    _DDCB-_00
                dc.w    _DDCC-_00
                dc.w    _DDCD-_00
                dc.w    _DDCE-_00
                dc.w    _DDCF-_00

                dc.w    _DDD0-_00
                dc.w    _DDD1-_00
                dc.w    _DDD2-_00
                dc.w    _DDD3-_00
                dc.w    _DDD4-_00
                dc.w    _DDD5-_00
                dc.w    _DDD6-_00
                dc.w    _DDD7-_00
                dc.w    _DDD8-_00
                dc.w    _DDD9-_00
                dc.w    _DDDA-_00
                dc.w    _DDDB-_00
                dc.w    _DDDC-_00
                dc.w    _DDDD-_00
                dc.w    _DDDE-_00
                dc.w    _DDDF-_00

                dc.w    _DDE0-_00
                dc.w    _DDE1-_00
                dc.w    _DDE2-_00
                dc.w    _DDE3-_00
                dc.w    _DDE4-_00
                dc.w    _DDE5-_00
                dc.w    _DDE6-_00
                dc.w    _DDE7-_00
                dc.w    _DDE8-_00
                dc.w    _DDE9-_00
                dc.w    _DDEA-_00
                dc.w    _DDEB-_00
                dc.w    _DDEC-_00
                dc.w    _DDED-_00
                dc.w    _DDEE-_00
                dc.w    _DDEF-_00

                dc.w    _DDF0-_00
                dc.w    _DDF1-_00
                dc.w    _DDF2-_00
                dc.w    _DDF3-_00
                dc.w    _DDF4-_00
                dc.w    _DDF5-_00
                dc.w    _DDF6-_00
                dc.w    _DDF7-_00
                dc.w    _DDF8-_00
                dc.w    _DDF9-_00
                dc.w    _DDFA-_00
                dc.w    _DDFB-_00
                dc.w    _DDFC-_00
                dc.w    _DDFD-_00
                dc.w    _DDFE-_00
                dc.w    _DDFF-_00

                dc.w    _FD00-_00
                dc.w    _FD01-_00
                dc.w    _FD02-_00
                dc.w    _FD03-_00
                dc.w    _FD04-_00
                dc.w    _FD05-_00
                dc.w    _FD06-_00
                dc.w    _FD07-_00
                dc.w    _FD08-_00
                dc.w    _FD09-_00
                dc.w    _FD0A-_00
                dc.w    _FD0B-_00
                dc.w    _FD0C-_00
                dc.w    _FD0D-_00
                dc.w    _FD0E-_00
                dc.w    _FD0F-_00

                dc.w    _FD10-_00
                dc.w    _FD11-_00
                dc.w    _FD12-_00
                dc.w    _FD13-_00
                dc.w    _FD14-_00
                dc.w    _FD15-_00
                dc.w    _FD16-_00
                dc.w    _FD17-_00
                dc.w    _FD18-_00
                dc.w    _FD19-_00
                dc.w    _FD1A-_00
                dc.w    _FD1B-_00
                dc.w    _FD1C-_00
                dc.w    _FD1D-_00
                dc.w    _FD1E-_00
                dc.w    _FD1F-_00

                dc.w    _FD20-_00
                dc.w    _FD21-_00
                dc.w    _FD22-_00
                dc.w    _FD23-_00
                dc.w    _FD24-_00
                dc.w    _FD25-_00
                dc.w    _FD26-_00
                dc.w    _FD27-_00
                dc.w    _FD28-_00
                dc.w    _FD29-_00
                dc.w    _FD2A-_00
                dc.w    _FD2B-_00
                dc.w    _FD2C-_00
                dc.w    _FD2D-_00
                dc.w    _FD2E-_00
                dc.w    _FD2F-_00
                           
                dc.w    _FD30-_00
                dc.w    _FD31-_00
                dc.w    _FD32-_00
                dc.w    _FD33-_00
                dc.w    _FD34-_00
                dc.w    _FD35-_00
                dc.w    _FD36-_00
                dc.w    _FD37-_00
                dc.w    _FD38-_00
                dc.w    _FD39-_00
                dc.w    _FD3A-_00
                dc.w    _FD3B-_00
                dc.w    _FD3C-_00
                dc.w    _FD3D-_00
                dc.w    _FD3E-_00
                dc.w    _FD3F-_00

                dc.w    _FD40-_00
                dc.w    _FD41-_00
                dc.w    _FD42-_00
                dc.w    _FD43-_00
                dc.w    _FD44-_00
                dc.w    _FD45-_00
                dc.w    _FD46-_00
                dc.w    _FD47-_00
                dc.w    _FD48-_00
                dc.w    _FD49-_00
                dc.w    _FD4A-_00
                dc.w    _FD4B-_00
                dc.w    _FD4C-_00
                dc.w    _FD4D-_00
                dc.w    _FD4E-_00
                dc.w    _FD4F-_00

                dc.w    _FD50-_00
                dc.w    _FD51-_00
                dc.w    _FD52-_00
                dc.w    _FD53-_00
                dc.w    _FD54-_00
                dc.w    _FD55-_00
                dc.w    _FD56-_00
                dc.w    _FD57-_00
                dc.w    _FD58-_00
                dc.w    _FD59-_00
                dc.w    _FD5A-_00
                dc.w    _FD5B-_00
                dc.w    _FD5C-_00
                dc.w    _FD5D-_00
                dc.w    _FD5E-_00
                dc.w    _FD5F-_00

                dc.w    _FD60-_00
                dc.w    _FD61-_00
                dc.w    _FD62-_00
                dc.w    _FD63-_00
                dc.w    _FD64-_00
                dc.w    _FD65-_00
                dc.w    _FD66-_00
                dc.w    _FD67-_00
                dc.w    _FD68-_00
                dc.w    _FD69-_00
                dc.w    _FD6A-_00
                dc.w    _FD6B-_00
                dc.w    _FD6C-_00
                dc.w    _FD6D-_00
                dc.w    _FD6E-_00
                dc.w    _FD6F-_00

                dc.w    _FD70-_00
                dc.w    _FD71-_00
                dc.w    _FD72-_00
                dc.w    _FD73-_00
                dc.w    _FD74-_00
                dc.w    _FD75-_00
                dc.w    _FD76-_00
                dc.w    _FD77-_00
                dc.w    _FD78-_00
                dc.w    _FD79-_00
                dc.w    _FD7A-_00
                dc.w    _FD7B-_00
                dc.w    _FD7C-_00
                dc.w    _FD7D-_00
                dc.w    _FD7E-_00
                dc.w    _FD7F-_00

                dc.w    _FD80-_00
                dc.w    _FD81-_00
                dc.w    _FD82-_00
                dc.w    _FD83-_00
                dc.w    _FD84-_00
                dc.w    _FD85-_00
                dc.w    _FD86-_00
                dc.w    _FD87-_00
                dc.w    _FD88-_00
                dc.w    _FD89-_00
                dc.w    _FD8A-_00
                dc.w    _FD8B-_00
                dc.w    _FD8C-_00
                dc.w    _FD8D-_00
                dc.w    _FD8E-_00
                dc.w    _FD8F-_00

                dc.w    _FD90-_00
                dc.w    _FD91-_00
                dc.w    _FD92-_00
                dc.w    _FD93-_00
                dc.w    _FD94-_00
                dc.w    _FD95-_00
                dc.w    _FD96-_00
                dc.w    _FD97-_00
                dc.w    _FD98-_00
                dc.w    _FD99-_00
                dc.w    _FD9A-_00
                dc.w    _FD9B-_00
                dc.w    _FD9C-_00
                dc.w    _FD9D-_00
                dc.w    _FD9E-_00
                dc.w    _FD9F-_00
                           
                dc.w    _FDA0-_00
                dc.w    _FDA1-_00
                dc.w    _FDA2-_00
                dc.w    _FDA3-_00
                dc.w    _FDA4-_00
                dc.w    _FDA5-_00
                dc.w    _FDA6-_00
                dc.w    _FDA7-_00
                dc.w    _FDA8-_00
                dc.w    _FDA9-_00
                dc.w    _FDAA-_00
                dc.w    _FDAB-_00
                dc.w    _FDAC-_00
                dc.w    _FDAD-_00
                dc.w    _FDAE-_00
                dc.w    _FDAF-_00

                dc.w    _FDB0-_00
                dc.w    _FDB1-_00
                dc.w    _FDB2-_00
                dc.w    _FDB3-_00
                dc.w    _FDB4-_00
                dc.w    _FDB5-_00
                dc.w    _FDB6-_00
                dc.w    _FDB7-_00
                dc.w    _FDB8-_00
                dc.w    _FDB9-_00
                dc.w    _FDBA-_00
                dc.w    _FDBB-_00
                dc.w    _FDBC-_00
                dc.w    _FDBD-_00
                dc.w    _FDBE-_00
                dc.w    _FDBF-_00

                dc.w    _FDC0-_00
                dc.w    _FDC1-_00
                dc.w    _FDC2-_00
                dc.w    _FDC3-_00
                dc.w    _FDC4-_00
                dc.w    _FDC5-_00
                dc.w    _FDC6-_00
                dc.w    _FDC7-_00
                dc.w    _FDC8-_00
                dc.w    _FDC9-_00
                dc.w    _FDCA-_00
                dc.w    _FDCB-_00
                dc.w    _FDCC-_00
                dc.w    _FDCD-_00
                dc.w    _FDCE-_00
                dc.w    _FDCF-_00

                dc.w    _FDD0-_00
                dc.w    _FDD1-_00
                dc.w    _FDD2-_00
                dc.w    _FDD3-_00
                dc.w    _FDD4-_00
                dc.w    _FDD5-_00
                dc.w    _FDD6-_00
                dc.w    _FDD7-_00
                dc.w    _FDD8-_00
                dc.w    _FDD9-_00
                dc.w    _FDDA-_00
                dc.w    _FDDB-_00
                dc.w    _FDDC-_00
                dc.w    _FDDD-_00
                dc.w    _FDDE-_00
                dc.w    _FDDF-_00

                dc.w    _FDE0-_00
                dc.w    _FDE1-_00
                dc.w    _FDE2-_00
                dc.w    _FDE3-_00
                dc.w    _FDE4-_00
                dc.w    _FDE5-_00
                dc.w    _FDE6-_00
                dc.w    _FDE7-_00
                dc.w    _FDE8-_00
                dc.w    _FDE9-_00
                dc.w    _FDEA-_00
                dc.w    _FDEB-_00
                dc.w    _FDEC-_00
                dc.w    _FDED-_00
                dc.w    _FDEE-_00
                dc.w    _FDEF-_00

                dc.w    _FDF0-_00
                dc.w    _FDF1-_00
                dc.w    _FDF2-_00
                dc.w    _FDF3-_00
                dc.w    _FDF4-_00
                dc.w    _FDF5-_00
                dc.w    _FDF6-_00
                dc.w    _FDF7-_00
                dc.w    _FDF8-_00
                dc.w    _FDF9-_00
                dc.w    _FDFA-_00
                dc.w    _FDFB-_00
                dc.w    _FDFC-_00
                dc.w    _FDFD-_00
                dc.w    _FDFE-_00
                dc.w    _FDFF-_00

                dc.w    _DDCB00-_00
                dc.w    _DDCB01-_00
                dc.w    _DDCB02-_00
                dc.w    _DDCB03-_00
                dc.w    _DDCB04-_00
                dc.w    _DDCB05-_00
                dc.w    _DDCB06-_00
                dc.w    _DDCB07-_00
                dc.w    _DDCB08-_00
                dc.w    _DDCB09-_00
                dc.w    _DDCB0A-_00
                dc.w    _DDCB0B-_00
                dc.w    _DDCB0C-_00
                dc.w    _DDCB0D-_00
                dc.w    _DDCB0E-_00
                dc.w    _DDCB0F-_00

                dc.w    _DDCB10-_00
                dc.w    _DDCB11-_00
                dc.w    _DDCB12-_00
                dc.w    _DDCB13-_00
                dc.w    _DDCB14-_00
                dc.w    _DDCB15-_00
                dc.w    _DDCB16-_00
                dc.w    _DDCB17-_00
                dc.w    _DDCB18-_00
                dc.w    _DDCB19-_00
                dc.w    _DDCB1A-_00
                dc.w    _DDCB1B-_00
                dc.w    _DDCB1C-_00
                dc.w    _DDCB1D-_00
                dc.w    _DDCB1E-_00
                dc.w    _DDCB1F-_00

                dc.w    _DDCB20-_00
                dc.w    _DDCB21-_00
                dc.w    _DDCB22-_00
                dc.w    _DDCB23-_00
                dc.w    _DDCB24-_00
                dc.w    _DDCB25-_00
                dc.w    _DDCB26-_00
                dc.w    _DDCB27-_00
                dc.w    _DDCB28-_00
                dc.w    _DDCB29-_00
                dc.w    _DDCB2A-_00
                dc.w    _DDCB2B-_00
                dc.w    _DDCB2C-_00
                dc.w    _DDCB2D-_00
                dc.w    _DDCB2E-_00
                dc.w    _DDCB2F-_00
                           
                dc.w    _DDCB30-_00
                dc.w    _DDCB31-_00
                dc.w    _DDCB32-_00
                dc.w    _DDCB33-_00
                dc.w    _DDCB34-_00
                dc.w    _DDCB35-_00
                dc.w    _DDCB36-_00
                dc.w    _DDCB37-_00
                dc.w    _DDCB38-_00
                dc.w    _DDCB39-_00
                dc.w    _DDCB3A-_00
                dc.w    _DDCB3B-_00
                dc.w    _DDCB3C-_00
                dc.w    _DDCB3D-_00
                dc.w    _DDCB3E-_00
                dc.w    _DDCB3F-_00

                dc.w    _DDCB40-_00
                dc.w    _DDCB41-_00
                dc.w    _DDCB42-_00
                dc.w    _DDCB43-_00
                dc.w    _DDCB44-_00
                dc.w    _DDCB45-_00
                dc.w    _DDCB46-_00
                dc.w    _DDCB47-_00
                dc.w    _DDCB48-_00
                dc.w    _DDCB49-_00
                dc.w    _DDCB4A-_00
                dc.w    _DDCB4B-_00
                dc.w    _DDCB4C-_00
                dc.w    _DDCB4D-_00
                dc.w    _DDCB4E-_00
                dc.w    _DDCB4F-_00

                dc.w    _DDCB50-_00
                dc.w    _DDCB51-_00
                dc.w    _DDCB52-_00
                dc.w    _DDCB53-_00
                dc.w    _DDCB54-_00
                dc.w    _DDCB55-_00
                dc.w    _DDCB56-_00
                dc.w    _DDCB57-_00
                dc.w    _DDCB58-_00
                dc.w    _DDCB59-_00
                dc.w    _DDCB5A-_00
                dc.w    _DDCB5B-_00
                dc.w    _DDCB5C-_00
                dc.w    _DDCB5D-_00
                dc.w    _DDCB5E-_00
                dc.w    _DDCB5F-_00

                dc.w    _DDCB60-_00
                dc.w    _DDCB61-_00
                dc.w    _DDCB62-_00
                dc.w    _DDCB63-_00
                dc.w    _DDCB64-_00
                dc.w    _DDCB65-_00
                dc.w    _DDCB66-_00
                dc.w    _DDCB67-_00
                dc.w    _DDCB68-_00
                dc.w    _DDCB69-_00
                dc.w    _DDCB6A-_00
                dc.w    _DDCB6B-_00
                dc.w    _DDCB6C-_00
                dc.w    _DDCB6D-_00
                dc.w    _DDCB6E-_00
                dc.w    _DDCB6F-_00

                dc.w    _DDCB70-_00
                dc.w    _DDCB71-_00
                dc.w    _DDCB72-_00
                dc.w    _DDCB73-_00
                dc.w    _DDCB74-_00
                dc.w    _DDCB75-_00
                dc.w    _DDCB76-_00
                dc.w    _DDCB77-_00
                dc.w    _DDCB78-_00
                dc.w    _DDCB79-_00
                dc.w    _DDCB7A-_00
                dc.w    _DDCB7B-_00
                dc.w    _DDCB7C-_00
                dc.w    _DDCB7D-_00
                dc.w    _DDCB7E-_00
                dc.w    _DDCB7F-_00

                dc.w    _DDCB80-_00
                dc.w    _DDCB81-_00
                dc.w    _DDCB82-_00
                dc.w    _DDCB83-_00
                dc.w    _DDCB84-_00
                dc.w    _DDCB85-_00
                dc.w    _DDCB86-_00
                dc.w    _DDCB87-_00
                dc.w    _DDCB88-_00
                dc.w    _DDCB89-_00
                dc.w    _DDCB8A-_00
                dc.w    _DDCB8B-_00
                dc.w    _DDCB8C-_00
                dc.w    _DDCB8D-_00
                dc.w    _DDCB8E-_00
                dc.w    _DDCB8F-_00

                dc.w    _DDCB90-_00
                dc.w    _DDCB91-_00
                dc.w    _DDCB92-_00
                dc.w    _DDCB93-_00
                dc.w    _DDCB94-_00
                dc.w    _DDCB95-_00
                dc.w    _DDCB96-_00
                dc.w    _DDCB97-_00
                dc.w    _DDCB98-_00
                dc.w    _DDCB99-_00
                dc.w    _DDCB9A-_00
                dc.w    _DDCB9B-_00
                dc.w    _DDCB9C-_00
                dc.w    _DDCB9D-_00
                dc.w    _DDCB9E-_00
                dc.w    _DDCB9F-_00
                           
                dc.w    _DDCBA0-_00
                dc.w    _DDCBA1-_00
                dc.w    _DDCBA2-_00
                dc.w    _DDCBA3-_00
                dc.w    _DDCBA4-_00
                dc.w    _DDCBA5-_00
                dc.w    _DDCBA6-_00
                dc.w    _DDCBA7-_00
                dc.w    _DDCBA8-_00
                dc.w    _DDCBA9-_00
                dc.w    _DDCBAA-_00
                dc.w    _DDCBAB-_00
                dc.w    _DDCBAC-_00
                dc.w    _DDCBAD-_00
                dc.w    _DDCBAE-_00
                dc.w    _DDCBAF-_00

                dc.w    _DDCBB0-_00
                dc.w    _DDCBB1-_00
                dc.w    _DDCBB2-_00
                dc.w    _DDCBB3-_00
                dc.w    _DDCBB4-_00
                dc.w    _DDCBB5-_00
                dc.w    _DDCBB6-_00
                dc.w    _DDCBB7-_00
                dc.w    _DDCBB8-_00
                dc.w    _DDCBB9-_00
                dc.w    _DDCBBA-_00
                dc.w    _DDCBBB-_00
                dc.w    _DDCBBC-_00
                dc.w    _DDCBBD-_00
                dc.w    _DDCBBE-_00
                dc.w    _DDCBBF-_00

                dc.w    _DDCBC0-_00
                dc.w    _DDCBC1-_00
                dc.w    _DDCBC2-_00
                dc.w    _DDCBC3-_00
                dc.w    _DDCBC4-_00
                dc.w    _DDCBC5-_00
                dc.w    _DDCBC6-_00
                dc.w    _DDCBC7-_00
                dc.w    _DDCBC8-_00
                dc.w    _DDCBC9-_00
                dc.w    _DDCBCA-_00
                dc.w    _DDCBCB-_00
                dc.w    _DDCBCC-_00
                dc.w    _DDCBCD-_00
                dc.w    _DDCBCE-_00
                dc.w    _DDCBCF-_00

                dc.w    _DDCBD0-_00
                dc.w    _DDCBD1-_00
                dc.w    _DDCBD2-_00
                dc.w    _DDCBD3-_00
                dc.w    _DDCBD4-_00
                dc.w    _DDCBD5-_00
                dc.w    _DDCBD6-_00
                dc.w    _DDCBD7-_00
                dc.w    _DDCBD8-_00
                dc.w    _DDCBD9-_00
                dc.w    _DDCBDA-_00
                dc.w    _DDCBDB-_00
                dc.w    _DDCBDC-_00
                dc.w    _DDCBDD-_00
                dc.w    _DDCBDE-_00
                dc.w    _DDCBDF-_00

                dc.w    _DDCBE0-_00
                dc.w    _DDCBE1-_00
                dc.w    _DDCBE2-_00
                dc.w    _DDCBE3-_00
                dc.w    _DDCBE4-_00
                dc.w    _DDCBE5-_00
                dc.w    _DDCBE6-_00
                dc.w    _DDCBE7-_00
                dc.w    _DDCBE8-_00
                dc.w    _DDCBE9-_00
                dc.w    _DDCBEA-_00
                dc.w    _DDCBEB-_00
                dc.w    _DDCBEC-_00
                dc.w    _DDCBED-_00
                dc.w    _DDCBEE-_00
                dc.w    _DDCBEF-_00

                dc.w    _DDCBF0-_00
                dc.w    _DDCBF1-_00
                dc.w    _DDCBF2-_00
                dc.w    _DDCBF3-_00
                dc.w    _DDCBF4-_00
                dc.w    _DDCBF5-_00
                dc.w    _DDCBF6-_00
                dc.w    _DDCBF7-_00
                dc.w    _DDCBF8-_00
                dc.w    _DDCBF9-_00
                dc.w    _DDCBFA-_00
                dc.w    _DDCBFB-_00
                dc.w    _DDCBFC-_00
                dc.w    _DDCBFD-_00
                dc.w    _DDCBFE-_00
                dc.w    _DDCBFF-_00
