;==================================================
;Подпрограмма обновления изменений на экране
;в режиме LoRes 2bpp (4 градации серого)

scr_upd_lr2bpp  move.l  zx_scr_tab(a5),a0
                move.l  palm_screen1(a5),a3
                move.l  #$aaaaaaaa,d4
                move.l  #$55555555,d5
                move.l  #96-1,d0
next_line_b     move.l  (a0)+,a1
                move.l  (a0)+,a2
                move.l  (a1)+,d1
                move.l  (a2)+,d2
                move.l  d1,d3
                or.l    d2,d1
                and.l   d2,d3
                move.l  d1,d2
                and.l   d5,d1
                and.l   d4,d2
                and.l   d4,d3
                add.l   d3,d2
                roxr.l  #1,d2
                add.l   d2,d1
                not.l   d1
                move.l  d1,(a3)+
                move.l  (a1)+,d1
                move.l  (a2)+,d2
                move.l  d1,d3
                or.l    d2,d1
                and.l   d2,d3
                move.l  d1,d2
                and.l   d5,d1
                and.l   d4,d2
                and.l   d4,d3
                add.l   d3,d2
                roxr.l  #1,d2
                add.l   d2,d1
                not.l   d1
                move.l  d1,(a3)+
                move.l  (a1)+,d1
                move.l  (a2)+,d2
                move.l  d1,d3
                or.l    d2,d1
                and.l   d2,d3
                move.l  d1,d2
                and.l   d5,d1
                and.l   d4,d2
                and.l   d4,d3
                add.l   d3,d2
                roxr.l  #1,d2
                add.l   d2,d1
                not.l   d1
                move.l  d1,(a3)+
                move.l  (a1)+,d1
                move.l  (a2)+,d2
                move.l  d1,d3
                or.l    d2,d1
                and.l   d2,d3
                move.l  d1,d2
                and.l   d5,d1
                and.l   d4,d2
                and.l   d4,d3
                add.l   d3,d2
                roxr.l  #1,d2
                add.l   d2,d1
                not.l   d1
                move.l  d1,(a3)+
                move.l  (a1)+,d1
                move.l  (a2)+,d2
                move.l  d1,d3
                or.l    d2,d1
                and.l   d2,d3
                move.l  d1,d2
                and.l   d5,d1
                and.l   d4,d2
                and.l   d4,d3
                add.l   d3,d2
                roxr.l  #1,d2
                add.l   d2,d1
                not.l   d1
                move.l  d1,(a3)+
                move.l  (a1)+,d1
                move.l  (a2)+,d2
                move.l  d1,d3
                or.l    d2,d1
                and.l   d2,d3
                move.l  d1,d2
                and.l   d5,d1
                and.l   d4,d2
                and.l   d4,d3
                add.l   d3,d2
                roxr.l  #1,d2
                add.l   d2,d1
                not.l   d1
                move.l  d1,(a3)+
                move.l  (a1)+,d1
                move.l  (a2)+,d2
                move.l  d1,d3
                or.l    d2,d1
                and.l   d2,d3
                move.l  d1,d2
                and.l   d5,d1
                and.l   d4,d2
                and.l   d4,d3
                add.l   d3,d2
                roxr.l  #1,d2
                add.l   d2,d1
                not.l   d1
                move.l  d1,(a3)+
                move.l  (a1),d1
                move.l  (a2),d2
                move.l  d1,d3
                or.l    d2,d1
                and.l   d2,d3
                move.l  d1,d2
                and.l   d5,d1
                and.l   d4,d2
                and.l   d4,d3
                add.l   d3,d2
                roxr.l  #1,d2
                add.l   d2,d1
                not.l   d1
                move.l  d1,(a3)
                adda    #12,a3
                dbra    d0,next_line_b
                rts
